### ISSUE TITLE
Error while creating the server is not reported

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/rsp-client#43]
The event mechanism and listeners does not allow to report server creation error as report by the status field

**Comment by jrichter1** [comment]
createServerAsync returns a Status object that contains any possible errors. Is that what you're looking for?

**Comment by adietish** [comment]
@jeffmaury dare to please specify what exactly you mean? And then, it would be great if we had steps to exemplify what's lacking.

**Comment by lstocchi** [comment]
If i create a server and during the creation there is an error (e.g create a server with a \ or / in the name) rsp-server returns the error message inside the status object but status code is always 0 (OK). Is this the issue you had @jeffmaury ?

**Comment by robstryker** [comment]
I can try to force this error to occur I guess? Specific use cases are preferred of course

**Comment by adietish** [comment]
@jeffmaury what exactly did you have in mind? dare to please provide more details?

**Comment by adietish** [comment]
@jeffmaury current implementation returns a ```
    export interface CreateServerResponse {
        status: Status;
        invalidKeys: string[];
    }
```

which holds a status object which specifies the success or failure. I don't have steps here to verify if things work as expected or not. Given that #155 is referring to this I tried to create a duplicate server, but couldn't. I thus assume that this bug is outdated. Closing.
