### ISSUE TITLE
Should include linter into build which errors if formatting is bad

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-client#69]
@jrichter1 in java this can be done via checkstyle. A build would error in maven if formatting doesn't fulfill certain rules (ex. the indentations that I missed). I bet something similar exists in ts?

**Comment by jrichter1** [comment]
tslint should be able to do it, hopefully

**Comment by jrichter1** [comment]
Most formatting is being checked during build, though the severity is set to 'warning' only.
The indentation rule seems to only care about whether one uses spaces or tabs though. The amount is simply ignored. That could be fixed by using an additional ruleset, but the question now is, how many spaces is the right amount...

**Comment by adietish** [comment]
@jrichter1 We both agree on the fact that indentation matters (see my PR where indentation was wrong). We should automate as much as we can and thus provide the additional ruleset that you mention. I have no strong opinion on how many spaces are right, 4 spaces (where spaces are preferred over tabs) seems like the most widely used convention to me.

**Comment by adietish** [comment]
An interesting option is to have the identation auto-fixed: https://palantir.github.io/tslint/rules/indent/
