### ISSUE TITLE
should replace hand-crafted request types by generated ones

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-client#74]
as discussed in https://github.com/redhat-developer/rsp-client/pull/66#issuecomment-463621547 we should generate request and responses in rsp-server and then used them in the rsp-client. If we have the request types bound to response types we'd have compile-time errors that warn us of API changes in the rsp-server

**Comment by robstryker** [comment]
Fixed in https://github.com/redhat-developer/rsp-client/pull/79  and  generation work done in:

* 5f874f6 - Much discussion on client timeouts (8 days ago) <Rob Stryker>
* a51d508 - More changes to generation (8 days ago) <Rob Stryker>
* 81207e4 - Adding 'Async' to each method name is dumb (9 days ago) <Rob Stryker>
* 0308290 - Small cleanup for client generation (9 days ago) <Rob Stryker>
